const languagePack = {
  'zh': {
    // ... existing zh language pack ...
    'logo-text': '宝鸡非遗皮影',
		    'nav-home': '首页',
		    'nav-heritage': '非遗文化',
		    'nav-products': '皮影产品',
		    'nav-masters': '非遗传承人',
		    'nav-process': '制作工艺',
		    'nav-shows': '皮影演出',
		    'nav-contact': '联系我们',
		    'hero-title': '国家级非物质文化遗产<br>宝鸡皮影',
		    'hero-subtitle': '千年技艺，光影传奇。传承中华文化瑰宝，展现皮影艺术魅力。',
		    'hero-explore': '探索非遗文化',
		    'hero-products': '查看皮影产品',
		    'heritage-title': '非遗文化',
		    'heritage-subtitle': '宝鸡皮影是中国传统民间艺术的瑰宝，有着深厚的历史文化底蕴和独特的艺术魅力',
		    'heritage-origin-title': '历史起源',
		    'heritage-origin-content': '宝鸡皮影历史悠久，起源于何时尚无定论，但至少可以追溯到明清时期。',
		    'heritage-feature-title': '艺术特色',
		    'heritage-feature-content': '宝鸡皮影以其精湛的雕刻技艺、绚丽的色彩和生动的造型而闻名。',
		    'heritage-protection-title': '传承保护',
		    'heritage-protection-content': '近年来，宝鸡皮影得到了政府和社会各界的重视与保护，通过建立传承基地、开展培训活动等方式，让这一古老艺术焕发出新的生机。',
		    'heritage-learn-more': '了解更多',
		    'heritage-history-title': '历史沿革',
		    'heritage-history-content': '宝鸡皮影的历史可以追溯到明清时期，经过数百年的发展，逐渐形成了自己独特的风格。在现代社会，随着科技的进步和人们生活方式的改变，宝鸡皮影面临着传承和发展的挑战。但通过政府和社会各界的努力，宝鸡皮影正逐渐焕发出新的生机。',
		    'heritage-history-more': '了解更多历史',
		    'products-title': '皮影产品',
		    'products-subtitle': '我们提供各种精美的皮影产品，包括传统人物、神话传说、动物造型等，适合收藏和装饰。',
		    'products-filter-all': '全部',
		    'products-filter-traditional': '传统人物',
		    'products-filter-myth': '神话传说',
		    'products-filter-animal': '动物造型',
		    'products-filter-modern': '现代创意',
		    'products-filter-peripheral': '文创周边',
		    'products-item1-title': '传统关羽皮影',
		    'products-item1-desc': '纯手工雕刻，色彩艳丽，造型生动',
		    'products-item2-title': '祥龙献瑞皮影',
		    'products-item2-desc': '大型龙形皮影，适合装饰与收藏',
		    'products-item3-title': '熊猫皮影摆件',
		    'products-item3-desc': '可爱熊猫造型，适合家居装饰',
		    'products-item4-title': '生肖全套皮影',
		    'products-item4-desc': '集齐十二种生肖，传统文化礼品',
		    'products-item5-title': '现代艺术皮影',
		    'products-item5-desc': '融合现代设计元素的创新皮影作品',
		    'products-item6-title': '贵妃醉酒皮影',
		    'products-item6-desc': '传统戏曲人物，工艺精湛',
		    'products-item7-title': '美猴王孙悟空',
		    'products-item7-desc': '《西游记》经典角色，造型生动',
		    'products-item8-title': '皮影工艺书签套装',
		    'products-item8-desc': '小巧精致的皮影工艺书签，一套6枚',
		    'products-more': '查看更多产品',
		    'masters-title': '非遗传承人',
		    'masters-subtitle': '他们是宝鸡皮影艺术的守护者，用一生的心血传承和发扬这门古老的技艺',
		    'masters-master1-name': '张明远',
		    'masters-master1-level': '国家级非遗传承人',
		    'masters-master1-desc': '从事皮影制作与表演四十余年，技艺精湛，擅长传统人物造型设计与雕刻。其作品曾多次在国内外展出并获奖。',
		    'masters-master2-name': '李桂芳',
		    'masters-master2-level': '省级非遗传承人',
		    'masters-master2-desc': '皮影表演艺术家，专注于皮影戏表演与传承工作，培养了众多优秀的皮影艺术人才，致力于让皮影艺术走进现代生活。',
		    'masters-master3-name': '王建国',
		    'masters-master3-level': '市级非遗传承人',
		    'masters-master3-desc': '创新型皮影艺术家，将现代设计理念与传统皮影技艺相结合，创作了一系列具有时代特色的皮影作品，深受年轻人喜爱。',
		    'masters-more': '了解更多传承人',
		    'process-title': '制作工艺',
		    'process-subtitle': '宝鸡皮影的制作工艺复杂精细，需要经过多道工序才能完成一件精美的皮影作品',
		    'process-step1-title': '选皮',
		    'process-step1-desc': '制作皮影的首选材料是牛皮，其次是驴皮和羊皮。选择质地坚韧、厚度均匀的皮革是制作优质皮影的基础。',
		    'process-step2-title': '制皮',
		    'process-step2-desc': '将选好的皮革经过浸泡、刮毛、去脂、晾晒等多道工序，制成薄而透明的皮料，为后续雕刻做准备。',
		    'process-step3-title': '画稿',
		    'process-step3-desc': '艺人们根据设计好的图案，用铅笔或毛笔在皮料上描绘出人物、动物或其他图案的轮廓，这需要艺人有扎实的绘画功底。',
		    'process-step4-title': '雕刻',
		    'process-step4-desc': '使用各种大小和形状的刀具，按照画稿的线条进行精细雕刻。雕刻是皮影制作的关键环节，需要艺人有丰富的经验和精湛的技巧。',
		    'process-step5-title': '上色',
		    'process-step5-desc': '用传统矿物颜料对雕刻好的皮影进行上色，色彩鲜艳，经久不褪。上色需要注意色彩的搭配和层次感，以增强皮影的艺术表现力。',
		    'process-step6-title': '组装',
		    'process-step6-desc': '将上色后的各个部件用线绳或细铁丝连接起来，安装操纵杆，使皮影能够活动自如，成为一个完整的表演道具。',
		    'process-more': '观看制作视频',
		    'shows-title': '皮影演出',
		    'shows-subtitle': '观看精彩的皮影表演，感受传统艺术的魅力与活力',
		    'shows-traditional-title': '传统皮影戏表演',
		    'shows-traditional-desc': '欣赏经典的传统皮影戏剧目，感受原汁原味的民间艺术魅力',
		    'shows-traditional-content': '我们的传统皮影戏表演由资深艺人团队演绎，剧目包括《白蛇传》、《西游记》等经典故事，表演生动精彩，让您领略传统皮影戏的艺术魅力。',
		    'shows-traditional-more': '了解更多',
		    'shows-modern-title': '现代皮影创新表演',
		    'shows-modern-desc': '融合现代元素的创新皮影表演，给传统艺术注入新的活力',
		    'shows-modern-content': '我们的创新皮影表演将传统技艺与现代音乐、灯光和剧情相结合，创作出适合现代观众的皮影剧目，如《丝路传奇》等，深受年轻人喜爱。',
		    'shows-modern-more': '了解更多',
		    'shows-teaching-title': '皮影体验课程',
		    'shows-teaching-desc': '想要亲身体验皮影制作的乐趣吗？我们提供专业的皮影体验课程，由非遗传承人亲自指导，让您在动手实践中感受皮影艺术的魅力。无论您是儿童还是成人，都能在这里找到创作的乐趣。',
		    'shows-teaching-basic': '基础体验课程',
		    'shows-teaching-basic-desc': '学习基础皮影制作，完成一个简单作品',
		    'shows-teaching-advanced': '高级创作课程',
		    'shows-teaching-advanced-desc': '深入学习皮影技艺，创作更复杂的作品',
		    'shows-teaching-more': '查看全部课程',
		    'contact-title': '联系我们',
		    'contact-subtitle': '如果您对宝鸡皮影感兴趣，或者有任何问题和建议，欢迎随时联系我们',
		    'contact-info': '联系方式',
		    'contact-address-title': '地址',
		    'contact-address': '陕西省宝鸡市渭滨区经二路155号宝鸡皮影博物馆',
		    'contact-phone-title': '电话',
		    'contact-email-title': '邮箱',
		    'contact-hours-title': '开放时间',
		    'contact-hours': '周二至周日 9:00-17:30<br>周一闭馆',
		    'contact-follow': '关注我们',
		    'contact-follow-desc': '关注我们的社交媒体账号，了解更多关于宝鸡皮影的最新动态和活动信息',
		    'contact-form-title': '发送消息',
		    'contact-name': '姓名',
		    'contact-email': '邮箱',
		    'contact-subject': '主题',
		    'contact-message': '消息',
		    'contact-send': '发送消息',
		    'footer-desc': '传承千年技艺，展现皮影魅力。让这门古老的艺术在现代社会焕发出新的生机。',
		    'footer-quicklinks': '快速链接',
		    'footer-products': '产品分类',
		    'footer-newsletter': '订阅我们',
		    'footer-newsletter-desc': '订阅我们的电子邮件，获取最新活动和优惠信息',
		    'footer-email-placeholder': '您的邮箱地址',
		    'footer-newsletter-agreement': '订阅即表示您同意我们的隐私政策和条款条件',
		    'footer-copyright': '© 2025 宝鸡非遗皮影. 保留所有权利.',
		    'footer-privacy': '隐私政策',
		    'footer-terms': '使用条款',
		    'footer-cookies': 'Cookie政策'
  },
  'en': {
    // ... existing en language pack ...
    'logo-text': 'Baoji Intangible Cultural Heritage Shadow Puppetry',
    'nav-home': 'Home',
    'nav-heritage': 'Heritage',
    'nav-products': 'Products',
    'nav-masters': 'Masters',
    'nav-process': 'Craftsmanship',
    'nav-shows': 'Performances',
    'nav-contact': 'Contact',
    'hero-title': 'National Intangible Cultural Heritage<br>Baoji Shadow Puppetry',
    'hero-subtitle': 'A millennium-old art form, a legend of light and shadow. Inheriting the treasures of Chinese culture and showcasing the charm of shadow puppetry art.',
    'hero-explore': 'Explore Heritage',
    'hero-products': 'View Products',
    'heritage-title': 'Intangible Cultural Heritage',
    'heritage-subtitle': 'Baoji Shadow Puppetry is a gem of Chinese traditional folk art, with a profound historical and cultural heritage and unique artistic charm.',
    'heritage-origin-title': 'Historical Origin',
    'heritage-origin-content': 'Baoji Shadow Puppetry has a long history. Its exact origin is still uncertain, but it can be traced back to at least the Ming and Qing Dynasties.',
    'heritage-feature-title': 'Artistic Features',
    'heritage-feature-content': 'Baoji Shadow Puppetry is known for its exquisite carving techniques, vibrant colors and vivid shapes.',
    'heritage-protection-title': 'Inheritance and Protection',
    'heritage-protection-content': 'In recent years, Baoji Shadow Puppetry has received attention and protection from the government and all sectors of society. Through the establishment of inheritance bases and training activities, this ancient art has regained new vitality.',
    'heritage-learn-more': 'Learn More',
    'heritage-history-title': 'Historical Development',
    'heritage-history-content': 'The history of Baoji Shadow Puppetry can be traced back to the Ming and Qing Dynasties. After hundreds of years of development, it has gradually formed its own unique style. In modern society, with the progress of technology and the changes in people\'s lifestyles, Baoji Shadow Puppetry is facing challenges in inheritance and development. However, through the efforts of the government and all sectors of society, Baoji Shadow Puppetry is gradually regaining its vitality.',
    'heritage-history-more': 'Learn More History',
    'products-title': 'Shadow Puppet Products',
    'products-subtitle': 'We offer a variety of exquisite shadow puppet products, including traditional characters, mythological legends, animal shapes, etc., suitable for collection and decoration.',
    'products-filter-all': 'All',
    'products-filter-traditional': 'Traditional Characters',
    'products-filter-myth': 'Mythological Legends',
    'products-filter-animal': 'Animal Shapes',
    'products-filter-modern': 'Modern Creative',
    'products-filter-peripheral': 'Cultural and Creative Products',
    'products-item1-title': 'Traditional Guan Yu Shadow Puppet',
    'products-item1-desc': 'Hand-carved with vibrant colors and vivid shapes',
    'products-item2-title': 'Lucky Dragon Shadow Puppet',
    'products-item2-desc': 'Large dragon-shaped shadow puppet, suitable for decoration and collection',
    'products-item3-title': 'Panda Shadow Puppet Decor',
    'products-item3-desc': 'Cute panda shape, suitable for home decoration',
    'products-item4-title': 'Zodiac Complete Set',
    'products-item4-desc': 'A complete set of twelve zodiac signs, a traditional cultural gift',
    'products-item5-title': 'Modern Art Shadow Puppet',
    'products-item5-desc': 'Innovative shadow puppet works integrating modern design elements',
    'products-item6-title': 'Concubine Yang Shadow Puppet',
    'products-item6-desc': 'Traditional opera character with exquisite craftsmanship',
    'products-item7-title': 'Monkey King Sun Wukong',
    'products-item7-desc': 'Classic character from "Journey to the West", vividly shaped',
    'products-item8-title': 'Shadow Puppet Craft Bookmark Set',
    'products-item8-desc': 'Small and delicate shadow puppet craft bookmarks, a set of 6',
    'products-more': 'View More Products',
    'masters-title': 'Intangible Cultural Heritage Masters',
    'masters-subtitle': 'They are the guardians of Baoji Shadow Puppetry art, inheriting and carrying forward this ancient art with their lifelong efforts.',
    'masters-master1-name': 'Zhang Mingyuan',
    'masters-master1-level': 'National Intangible Cultural Heritage Master',
    'masters-master1-desc': 'With more than 40 years of experience in shadow puppet production and performance, he is skilled in traditional character modeling design and carving. His works have been exhibited and awarded at home and abroad for many times.',
    'masters-master2-name': 'Li Guifang',
    'masters-master2-level': 'Provincial Intangible Cultural Heritage Master',
    'masters-master2-desc': 'A shadow puppet performance artist, focusing on shadow puppet show performance and inheritance work, training many excellent shadow puppet art talents, and committed to bringing shadow puppet art into modern life.',
    'masters-master3-name': 'Wang Jianguo',
    'masters-master3-level': 'Municipal Intangible Cultural Heritage Master',
    'masters-master3-desc': 'An innovative shadow puppet artist who combines modern design concepts with traditional shadow puppet techniques to create a series of shadow puppet works with contemporary characteristics, which are very popular among young people.',
    'masters-more': 'Learn More Masters',
    'process-title': 'Craftsmanship',
    'process-subtitle': 'The production process of Baoji Shadow Puppetry is complex and delicate, requiring multiple processes to complete a beautiful shadow puppet work.',
    'process-step1-title': 'Material Selection',
    'process-step1-desc': 'The preferred material for making shadow puppets is cowhide, followed by donkey hide and sheepskin. Selecting leather with tough texture and uniform thickness is the foundation for making high-quality shadow puppets.',
    'process-step2-title': 'Leather Preparation',
    'process-step2-desc': 'The selected leather goes through multiple processes such as soaking, hair removal, degreasing, and drying to make a thin and transparent leather material for subsequent carving.',
    'process-step3-title': 'Drafting',
    'process-step3-desc': 'Artists draw the outlines of characters, animals or other patterns on the leather with pencils or brushes according to the designed patterns, which requires artists to have solid painting skills.',
    'process-step4-title': 'Carving',
    'process-step4-desc': 'Use various sizes and shapes of knives to carefully carve according to the lines of the draft. Carving is a key link in shadow puppet production, requiring artists to have rich experience and exquisite skills.',
    'process-step5-title': 'Coloring',
    'process-step5-desc': 'Color the carved shadow puppets with traditional mineral pigments, with bright colors that last forever. Coloring requires attention to color matching and layering to enhance the artistic expression of shadow puppets.',
    'process-step6-title': 'Assembly',
    'process-step6-desc': 'Connect the colored parts with strings or thin wires, and install the control rods to make the shadow puppet move freely and become a complete performance prop.',
    'process-more': 'Watch Production Video',
    'shows-title': 'Shadow Puppet Performances',
    'shows-subtitle': 'Watch wonderful shadow puppet shows and feel the charm and vitality of traditional art.',
    'shows-traditional-title': 'Traditional Shadow Puppet Show',
    'shows-traditional-desc': 'Appreciate classic traditional shadow puppet shows and feel the authentic charm of folk art.',
    'shows-traditional-content': 'Our traditional shadow puppet shows are performed by a team of senior artists. The repertoires include classic stories such as "The Legend of White Snake" and "Journey to the West". The performances are vivid and wonderful, allowing you to appreciate the artistic charm of traditional shadow puppet shows.',
    'shows-traditional-more': 'Learn More',
    'shows-modern-title': 'Modern Shadow Puppet Innovation Performance',
    'shows-modern-desc': 'An innovative shadow puppet performance integrating modern elements, injecting new vitality into traditional art.',
    'shows-modern-content': 'Our innovative shadow puppet performances combine traditional techniques with modern music, lighting and plots to create shadow puppet repertoires suitable for modern audiences, such as "The Legend of the Silk Road", which are very popular among young people.',
    'shows-modern-more': 'Learn More',
    'shows-teaching-title': 'Shadow Puppet Experience Course',
    'shows-teaching-desc': 'Want to experience the fun of making shadow puppets? We offer professional shadow puppet experience courses, personally guided by intangible cultural heritage masters, allowing you to feel the charm of shadow puppet art through hands-on practice. Whether you are a child or an adult, you can find creative fun here.',
    'shows-teaching-basic': 'Basic Experience Course',
    'shows-teaching-basic-desc': 'Learn basic shadow puppet production and complete a simple work',
    'shows-teaching-advanced': 'Advanced Creation Course',
    'shows-teaching-advanced-desc': 'Deeply learn shadow puppet techniques and create more complex works',
    'shows-teaching-more': 'View All Courses',
    'contact-title': 'Contact Us',
    'contact-subtitle': 'If you are interested in Baoji Shadow Puppetry, or have any questions and suggestions, please feel free to contact us.',
    'contact-info': 'Contact Information',
    'contact-address-title': 'Address',
    'contact-address': 'Baoji Shadow Puppetry Museum, No. 155 Jing er Road, Weibin District, Baoji City, Shaanxi Province',
    'contact-phone-title': 'Phone',
    'contact-email-title': 'Email',
    'contact-hours-title': 'Opening Hours',
    'contact-hours': 'Tuesday to Sunday 9:00-17:30<br>Closed on Monday',
    'contact-follow': 'Follow Us',
    'contact-follow-desc': 'Follow our social media accounts to learn more about the latest developments and event information of Baoji Shadow Puppetry.',
    'contact-form-title': 'Send Message',
    'contact-name': 'Name',
    'contact-email': 'Email',
    'contact-subject': 'Subject',
    'contact-message': 'Message',
    'contact-send': 'Send Message',
    'footer-desc': 'Inheriting a millennium-old art, showcasing the charm of shadow puppetry. Let this ancient art glow with new vitality in modern society.',
    'footer-quicklinks': 'Quick Links',
    'footer-products': 'Product Categories',
    'footer-newsletter': 'Subscribe to Us',
    'footer-newsletter-desc': 'Subscribe to our email to get the latest events and promotional information.',
    'footer-email-placeholder': 'Your email address',
    'footer-newsletter-agreement': 'Subscribing indicates that you agree to our Privacy Policy and Terms of Service.',
    'footer-copyright': '© 2025 Baoji Intangible Cultural Heritage Shadow Puppetry. All rights reserved.',
    'footer-privacy': 'Privacy Policy',
    'footer-terms': 'Terms of Service',
    'footer-cookies': 'Cookie Policy'
  }
};

export default languagePack;